export const shadows = [
  "bg-[conic-gradient(var(--tw-gradient-stops))] from-gray-600 via-red-600 to-purple-600",
  "bg-gradient-to-l from-orange-600 via-neutral-600 to-teal-600",
  "bg-[radial-gradient(ellipse_at_bottom,_var(--tw-gradient-stops))] from-blue-600 via-sky-600 to-cyan-600",
  "bg-[conic-gradient(at_bottom_left,_var(--tw-gradient-stops))] from-gray-600 via-stone-600 to-sky-600",
  "bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-violet-600 via-orange-600 to-zinc-600",
  "bg-gradient-to-l from-sky-600 via-cyan-600 to-lime-600",
  "bg-[conic-gradient(at_right,_var(--tw-gradient-stops))] from-yellow-600 via-amber-600 to-slate-600",
  "bg-[radial-gradient(ellipse_at_right,_var(--tw-gradient-stops))] from-orange-600 via-cyan-600 to-pink-600",
  "bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-gray-600 via-stone-600 to-green-600",
  "bg-[conic-gradient(at_bottom_left,_var(--tw-gradient-stops))] from-rose-600 via-blue-600 to-sky-600",
  "bg-[conic-gradient(at_right,_var(--tw-gradient-stops))] from-pink-600 via-lime-600 to-emerald-600",
  "bg-gradient-to-b from-amber-600 via-zinc-600 to-amber-600",
  "bg-[radial-gradient(ellipse_at_right,_var(--tw-gradient-stops))] from-amber-600 via-emerald-600 to-purple-600",
  "bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-yellow-600 via-emerald-600 to-green-600",
  "bg-gradient-to-tl from-fuchsia-600 via-sky-600 to-lime-600",
  "bg-gradient-to-br from-purple-600 via-pink-600 to-emerald-600",
  "bg-gradient-to-tr from-neutral-600 via-pink-600 to-gray-600",
  "bg-[conic-gradient(at_top,_var(--tw-gradient-stops))] from-emerald-600 via-amber-600 to-stone-600"
]
